# GitHub workflow for TensorFlow2 Reinforcement Learning Cookbook
name: TFRL-Cookbook-CI

on:
  # Enable workflow trigger on push/PR to master when the workflow is finalized
  # push:
  #  branches: [ master ]
  # pull_request:
  #  branches: [ master ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gen-notebooks :
    runs-on: ubuntu-20.04
    steps:
      # Checkout code to $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Install basic dependencies
        run: |
            sudo apt update
            sudo apt install -y make cmake ffmpeg freeglut3-dev
      - name: Setup tfrl-cookbook conda py env
        run: |
            wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
            bash miniconda.sh -b -p $HOME/miniconda
            source $HOME/miniconda/bin/activate
            conda init bash
            conda env create --force -f tfrl-cookbook.yml -n "tfrl-cookbook"
      - name: Install jupytext & setup ipykernel
        run: |
            source $HOME/miniconda/bin/activate
            conda activate tfrl-cookbook
            python -m pip install jupytext
            python -m ipykernel install --user --name=tfrl-cookbook

      - name: Ch1 generate .ipynb & .md
        run: |
            source $HOME/miniconda/bin/activate
            conda activate tfrl-cookbook
            for fname in `find ./Chapter01 -name "[0-9]*.py"`;do jupytext --set-formats ipynb,py --execute $fname; done;
            for fname in `find ./Chapter01 -name "[0-9]*.ipynb"`;do jupyter nbconvert $fname --to markdown; done;

      - name: Ch2 generate .ipynb & .md
        run: |
            source $HOME/miniconda/bin/activate
            conda activate tfrl-cookbook
            for fname in `find ./Chapter02 -name "[0-9]*.py"`;do jupytext --set-formats ipynb,py --execute $fname; done;
            for fname in `find ./Chapter02 -name "[0-9]*.ipynb"`;do jupyter nbconvert $fname --to markdown; done;

      - name: Ch3 Convert parse_args() to parse_args([]) to allow ipynb to execute
        run: find ./Chapter03 -name "[0-9]*.py" -exec sed -i 's/parser.parse_args()/parser.parse_args(\[\])/g' {} \;
      - name: Ch3 generate .ipynb & .md
        run: |
            source $HOME/miniconda/bin/activate
            conda activate tfrl-cookbook
            for fname in `find ./Chapter03 -name "[0-9]*.py"`;do jupytext --set-formats ipynb,py --execute $fname; done;
            for fname in `find ./Chapter03 -name "[0-9]*.ipynb"`;do jupyter nbconvert $fname --to markdown; done;

      - name: Ch6 Convert parse_args() to parse_args([]) to allow ipynb to execute
        run: find ./Chapter06 -name "[0-9]*.py" -exec sed -i 's/parser.parse_args()/parser.parse_args(\[\])/g' {} \;
      # - name: Ch6 generate .ipynb & .md
      #  run: |
      #      source $HOME/miniconda/bin/activate
      #      conda activate tfrl-cookbook
      #      for fname in `find ./Chapter06 -name "[0-9]*.py"`;do jupytext --set-formats ipynb,py --execute $fname; done;
      #      for fname in `find ./Chapter06 -name "[0-9]*.ipynb"`;do jupyter nbconvert $fname --to markdown; done;

      - name: Commit notebooks
        run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add *.ipynb
            git commit -m "Updated notebooks"
      - name: Push notebooks
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: refs/heads/notebooks
